name: Install.sh

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: sudo apt update && sudo apt install -y curl wget
            - name: Install termscp from script
              run: |
                  ./install.sh -v=0.10.0 -f
                  which termscp || exit 1
