name: Install.sh

on:
  push:
    branches: [main]
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y curl wget libsmbclient
      - name: Install termscp from script
        run: |
          ./install.sh -v=0.12.3 -f
          which termscp || exit 1
